name: Test
on:
  push: ~
  pull_request: ~

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: Calculate Perl Versions
    steps:
      - uses: actions/checkout@v4
      - id: perl-versions
        uses: perl-actions/perl-versions@v1
        with:
          # we are compatible with 5.8, but some prereqs no longer are
          since-perl: 5.12
          with-devel: true
      - id: perl-images
        uses: actions/github-script@v8
        env:
          PERL_VERSIONS: ${{ steps.perl-versions.outputs.perl-versions }}
        with:
          script: |
            const versions = JSON.parse(process.env.PERL_VERSIONS);
            const images = versions.map(v => {
              const vparts = v.split(/\./);
              let image = `perl:${v}`;
              if (vparts[0] == 5 && vparts[1] <= 24) {
                image += '-buster';
              }
              return image;
            });
            return images;
    outputs:
      versions: ${{ steps.perl-versions.outputs.perl-versions }}
      images: ${{steps.perl-images.outputs.result}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.perl-cpm
          key: cpm-${{ runner.os }}
      - name: Setup local::lib
        run: |
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5:$PERL5LIB" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
      - name: Extract Dist::Zilla dependencies
        id: authordeps
        uses: perl-actions/get-prereqs@v1
        with:
          sources: dist.ini
          phases: author
          exclude: '^inc::'
      - name: Install authordeps
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          install: ${{ steps.authordeps.outputs.prereqs }}
      - name: Build
        id: build
        run: |
          DZIL_COLOR=1 dzil build --no-tgz | tee "/tmp/dzil-build.log"
          echo build="$(grep --only-matching 'built in .*' "/tmp/dzil-build.log" | tail -1 | cut -c10-)" >> "$GITHUB_OUTPUT"
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.build }}
          path: ${{ steps.build.outputs.build }}
          include-hidden-files: true
    outputs:
      name: ${{ steps.build.outputs.build }}

  test:
    needs:
      - perl-versions
      - build

    strategy:
      fail-fast: false
      matrix:
        perl-image: ${{ fromJson(needs.perl-versions.outputs.images) }}

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.perl-image }}

    env:
      AUTOMATED_TESTING: 1
      PERL_USE_UNSAFE_INC: 0

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.name }}
      - uses: actions/cache@v4
        with:
          path: ~/.perl-cpm
          key: cpm-${{ job.container }}
      - name: Setup local::lib
        run: |
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5:$PERL5LIB" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
      - name: Extract configure dependecies
        id: configure
        uses: perl-actions/get-prereqs@v1
        with:
          phases: configure
      - name: Install configure deps
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          install: ${{ steps.configure.outputs.prereqs }}
      - name: Run Makefile.PL
        run: perl Makefile.PL
      - name: Extract dependecies
        id: prereqs
        uses: perl-actions/get-prereqs@v1
        with:
          phases: build test runtime
          relationships: requires recommends suggests
      - name: Install deps
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          install: ${{ steps.prereqs.outputs.prereqs }}
      - name: Run the tests
        run: make test

  test-xt:
    needs:
      - perl-versions
      - build

    runs-on: ubuntu-latest
    container:
      image: perl:5.40

    env:
      AUTOMATED_TESTING: 1

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.name }}
      - uses: actions/cache@v4
        with:
          path: ~/.perl-cpm
          key: cpm-${{ job.container }}
      - name: Setup local::lib
        run: |
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5:$PERL5LIB" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
      - name: Extract configure dependecies
        id: configure
        uses: perl-actions/get-prereqs@v1
        with:
          phases: configure
      - name: Install configure deps
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          install: ${{ steps.configure.outputs.prereqs }}
      - name: Run Makefile.PL
        run: perl Makefile.PL
      - name: Extract dependecies
        id: prereqs
        uses: perl-actions/get-prereqs@v1
        with:
          phases: build test runtime develop
          relationships: requires recommends suggests
      - name: Install deps
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          install: ${{ steps.prereqs.outputs.prereqs }}
      - name: Run the xt tests
        if: hashFiles('xt/*.t')
        run: prove -l xt
        env:
          AUTHOR_TESTING: 1
      - name: Run the xt/author tests
        if: hashFiles('xt/author/**/*.t')
        run: prove -lr xt/author
        env:
          AUTHOR_TESTING: 1
